#!/bin/bash
# Make the SEAMM directory if it doesn't exist
if [ ! -d ~/SEAMM ]; then
mkdir -p ~/SEAMM
fi

/usr/local/bin/docker compose --file ~/Applications/Dashboard.app/Contents/Resources/seamm-environment.yaml up -d 
