#!/bin/bash

# Make the SEAMM directory if it doesn't exist
directory=~/SEAMM
if [ ! -d $directory ]; then
    mkdir -p $directory
fi

# And the ~/.seamm directory
directory=~/.seamm
if [ ! -d $directory ]; then
    mkdir -p $directory
    if [ ! -f ~/.seammrc ]; then
	mv ~/.seammrc ~/.seamm/seammrc
    fi
fi

/usr/local/bin/docker run --pull always --rm --name SEAMM \
		      --env "DISPLAY=host.docker.internal:0" \
		      --network seamm-network \
		      -v ~/SEAMM:/root/SEAMM \
		      -v ~/.seamm:/root/.seamm \
		      ghcr.io/molssi-seamm/seamm:latest &
